In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv('/content/final_3K - Final.csv')

In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  Axiss Dental Clinic, Malleshwaram, Bangalore p...                        0   
1  This hospital is backed by cutting edge medica...                        0   
2  This hospital has rooms that are eqipped with ...                        0   
3  Axiss Dental Clinic, Rajouri Garden, New Delhi...                        0   
4  This hospital uses international standards as ...                        0   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0      1.0         NaN        NaN          NaN       NaN                NaN   
1      1.0         NaN        NaN          NaN       5.0                NaN   
2      1.0         NaN        NaN          NaN       NaN                6.0   
3      1.0         NaN        NaN          NaN       NaN                6.0   
4      1.0         2.0        NaN          NaN       5.0                NaN   

   Inefficiency  Unavailibility  Billing  
0           NaN             NaN      NaN  
1           NaN             NaN      NaN  
2           NaN             NaN      NaN  
3           NaN             NaN      NaN  
4           NaN             NaN      NaN

In [ ]:
col = ['Complaint/Non Complaint', 'Service','Negligence',	'Behaviour','Cleanliness','Pharmacy','Unprofessionalism',	'Inefficiency',	'Unavailibility',	'Billing']

In [ ]:
df[col] = df[col].fillna(0)
df[col] = df[col].astype(int)

In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  Axiss Dental Clinic, Malleshwaram, Bangalore p...                        0   
1  This hospital is backed by cutting edge medica...                        0   
2  This hospital has rooms that are eqipped with ...                        0   
3  Axiss Dental Clinic, Rajouri Garden, New Delhi...                        0   
4  This hospital uses international standards as ...                        0   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0        1           0          0            0         0                  0   
1        1           0          0            0         5                  0   
2        1           0          0            0         0                  6   
3        1           0          0            0         0                  6   
4        1           2          0            0         5                  0   

   Inefficiency  Unavailibility  Billing  
0             0               0        0  
1             0               0        0  
2             0               0        0  
3             0               0        0  
4             0               0        0

In [ ]:
df.replace('', pd.NA, inplace=True)

In [ ]:
import numpy as np

actual = []

for index, row in df.iterrows():
    temp_list = [value for value in row[2:] if pd.notna(value) and np.any(value != 0)]
    actual.append(temp_list)

df['Actual'] = actual



In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  Axiss Dental Clinic, Malleshwaram, Bangalore p...                        0   
1  This hospital is backed by cutting edge medica...                        0   
2  This hospital has rooms that are eqipped with ...                        0   
3  Axiss Dental Clinic, Rajouri Garden, New Delhi...                        0   
4  This hospital uses international standards as ...                        0   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0        1           0          0            0         0                  0   
1        1           0          0            0         5                  0   
2        1           0          0            0         0                  6   
3        1           0          0            0         0                  6   
4        1           2          0            0         5                  0   

   Inefficiency  Unavailibility  Billing     Actual  
0             0               0        0        [1]  
1             0               0        0     [1, 5]  
2             0               0        0     [1, 6]  
3             0               0        0     [1, 6]  
4             0               0        0  [1, 2, 5]

In [ ]:
df.to_csv('final_3k.csv', index=False)

In [ ]:
import ast
import pandas as pd

df = pd.read_csv('/content/mistral.csv')
fnl = []

for lst_str in df['Multilabel pred']:
    lst = ast.literal_eval(lst_str)  # Convert string representation of list to actual list
    intr = []
    for i in range(1, 10):  # Changed range from 9 to 10, and starting index from 0 to 1
        if i in lst:
            intr.append(1)
        else:
            intr.append(0)
    fnl.append(intr)

df['1hot_pred'] = fnl  # Adding the new column to the DataFrame


In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  BBH is the best hospital all the employees are...                        0   
1  Good Hospital. Excellent care given. Pleasant ...                        0   
2  From the past six months, iam going through he...                        0   
3  Daughters ear piercing done in most horrible w...                        1   
4  I was admitted for a DNS operation .which has ...                        1   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0      1.0         NaN        3.0          NaN       NaN                NaN   
1      1.0         NaN        NaN          4.0       NaN                6.0   
2      1.0         NaN        NaN          NaN       NaN                6.0   
3      1.0         2.0        3.0          NaN       NaN                NaN   
4      1.0         NaN        3.0          NaN       NaN                6.0   

   Inefficiency  Unavailibility  Billing Multilabels  word_count  Binary Pred  \
0           NaN             NaN      NaN      [1, 3]          14            0   
1           NaN             NaN      NaN   [1, 4, 6]          14            0   
2           7.0             NaN      NaN   [1, 6, 7]          39            0   
3           NaN             NaN      NaN   [1, 2, 3]          33            1   
4           NaN             NaN      NaN   [1, 3, 6]          51            1   

   Multilabel pred                    1hot_pred  
0              [3]  [0, 0, 1, 0, 0, 0, 0, 0, 0]  
1              [1]  [1, 0, 0, 0, 0, 0, 0, 0, 0]  
2              [3]  [0, 0, 1, 0, 0, 0, 0, 0, 0]  
3           [2, 3]  [0, 1, 1, 0, 0, 0, 0, 0, 0]  
4  [1, 2, 3, 4, 6]  [1, 1, 1, 1, 0, 1, 0, 0, 0]

In [ ]:
fnl = []

for lst_str in df['Multilabels']:
    lst = ast.literal_eval(lst_str)  # Convert string representation of list to actual list
    intr = []
    for i in range(1, 10):  # Changed range from 9 to 10, and starting index from 0 to 1
        if i in lst:
            intr.append(1)
        else:
            intr.append(0)
    fnl.append(intr)

df['1hot_act'] = fnl  # Adding the new column to the DataFrame


In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  BBH is the best hospital all the employees are...                        0   
1  Good Hospital. Excellent care given. Pleasant ...                        0   
2  From the past six months, iam going through he...                        0   
3  Daughters ear piercing done in most horrible w...                        1   
4  I was admitted for a DNS operation .which has ...                        1   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0      1.0         NaN        3.0          NaN       NaN                NaN   
1      1.0         NaN        NaN          4.0       NaN                6.0   
2      1.0         NaN        NaN          NaN       NaN                6.0   
3      1.0         2.0        3.0          NaN       NaN                NaN   
4      1.0         NaN        3.0          NaN       NaN                6.0   

   Inefficiency  Unavailibility  Billing Multilabels  word_count  Binary Pred  \
0           NaN             NaN      NaN      [1, 3]          14            0   
1           NaN             NaN      NaN   [1, 4, 6]          14            0   
2           7.0             NaN      NaN   [1, 6, 7]          39            0   
3           NaN             NaN      NaN   [1, 2, 3]          33            1   
4           NaN             NaN      NaN   [1, 3, 6]          51            1   

   Multilabel pred                    1hot_pred                     1hot_act  
0              [3]  [0, 0, 1, 0, 0, 0, 0, 0, 0]  [1, 0, 1, 0, 0, 0, 0, 0, 0]  
1              [1]  [1, 0, 0, 0, 0, 0, 0, 0, 0]  [1, 0, 0, 1, 0, 1, 0, 0, 0]  
2              [3]  [0, 0, 1, 0, 0, 0, 0, 0, 0]  [1, 0, 0, 0, 0, 1, 1, 0, 0]  
3           [2, 3]  [0, 1, 1, 0, 0, 0, 0, 0, 0]  [1, 1, 1, 0, 0, 0, 0, 0, 0]  
4  [1, 2, 3, 4, 6]  [1, 1, 1, 1, 0, 1, 0, 0, 0]  [1, 0, 1, 0, 0, 1, 0, 0, 0]

In [ ]:

from sklearn.metrics import multilabel_confusion_matrix, classification_report
import numpy as np

y_true = np.array(df['1hot_act'].tolist())
y_pred = np.array(df['1hot_pred'].tolist())

# Calculate multilabel confusion matrix
confusion_matrices = multilabel_confusion_matrix(y_true, y_pred)

# Display confusion matrices
for i, confusion_matrix in enumerate(confusion_matrices):
    print(f'Confusion matrix for label {i + 1}:')
    print(confusion_matrix)


Confusion matrix for label 1:
[[  93   84]
 [1200 1433]]
Confusion matrix for label 2:
[[1597  408]
 [ 440  365]]
Confusion matrix for label 3:
[[531 876]
 [417 986]]
Confusion matrix for label 4:
[[1450 1088]
 [  64  208]]
Confusion matrix for label 5:
[[2227  453]
 [  97   33]]
Confusion matrix for label 6:
[[ 744  318]
 [1129  619]]
Confusion matrix for label 7:
[[1548  478]
 [ 549  235]]
Confusion matrix for label 8:
[[1929  511]
 [ 277   93]]
Confusion matrix for label 9:
[[1832  225]
 [ 422  331]]


In [ ]:
from sklearn.metrics import classification_report
import pprint

report = classification_report(
    y_true,
    y_pred,
    output_dict=True,
    target_names=['Service', 'Negligence', 'Behaviour', 'Cleanliness', 'Pharmacy', 'Unprofessionalism', 'Inefficiency', 'Unavailability', 'Billing']
)

pprint.pprint(report)


{'Behaviour': {'f1-score': 0.6039816232771822,
               'precision': 0.5295381310418904,
               'recall': 0.7027797576621525,
               'support': 1403},
 'Billing': {'f1-score': 0.505729564553094,
             'precision': 0.5953237410071942,
             'recall': 0.4395750332005312,
             'support': 753},
 'Cleanliness': {'f1-score': 0.26530612244897955,
                 'precision': 0.16049382716049382,
                 'recall': 0.7647058823529411,
                 'support': 272},
 'Inefficiency': {'f1-score': 0.3139612558450234,
                  'precision': 0.32959326788218796,
                  'recall': 0.2997448979591837,
                  'support': 784},
 'Negligence': {'f1-score': 0.4626108998732573,
                'precision': 0.4721862871927555,
                'recall': 0.453416149068323,
                'support': 805},
 'Pharmacy': {'f1-score': 0.10714285714285714,
              'precision': 0.06790123456790123,
              'recall': 0.2

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import sklearn.metrics

print('Exact Match Ratio: {0}'.format(sklearn.metrics.accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)))
#Exact Match Ratio: 0.25

print('Hamming loss: {0}'.format(sklearn.metrics.hamming_loss(y_true, y_pred)))
#Hamming loss: 0.4166666666666667

#"samples" applies only to multilabel problems. It does not calculate a per-class measure, instead calculating the metric over the true and predicted classes
#for each sample in the evaluation data, and returning their (sample_weight-weighted) average.

print('Recall: {0}'.format(sklearn.metrics.precision_score(y_true=y_true, y_pred=y_pred, average='samples')))
#Recall: 0.375

print('Precision: {0}'.format(sklearn.metrics.recall_score(y_true=y_true, y_pred=y_pred, average='samples')))
#Precision: 0.5

print('F1 Measure: {0}'.format(sklearn.metrics.f1_score(y_true=y_true, y_pred=y_pred, average='samples')))
#F1 Measure: 0.41666666666666663

Exact Match Ratio: 0.022775800711743774
Hamming loss: 0.3572953736654804
Recall: 0.5662898943681862
Precision: 0.4725482968988306
F1 Measure: 0.43971181384149777


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
df = pd.read_csv('/content/mistral_millab.csv')

In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  Rainbow hospital will loot your hard earned mo...                        1   
1  My seven-months old baby had second-degree bur...                        1   
2  Very unprofessional .\nShe will not give you e...                        1   
3  The staff are extremely caring and hard workin...                        0   
4  Very expensive Lab Tests and I don't know why ...                        1   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0      1.0         NaN        NaN          NaN       NaN                NaN   
1      1.0         2.0        3.0          NaN       NaN                6.0   
2      1.0         NaN        NaN          NaN       NaN                6.0   
3      1.0         NaN        3.0          NaN       NaN                6.0   
4      NaN         2.0        NaN          NaN       NaN                NaN   

   Inefficiency  Unavailibility  Billing         Multilabels  word_count  \
0           NaN             NaN      9.0              [1, 9]          58   
1           7.0             NaN      9.0  [1, 2, 3, 6, 7, 9]          91   
2           7.0             NaN      NaN           [1, 6, 7]          63   
3           NaN             NaN      NaN           [1, 3, 6]          24   
4           NaN             NaN      9.0              [2, 9]          39   

   Binary Pred  Predictions                                    Multilabel pred  
0            1            1  [Unprofessionalism, Inefficiency, Unavailibility]  
1            0            0                  [Unprofessionalism, Inefficiency]  
2            1            1                                [Unprofessionalism]  
3            0            0                               [Service, Behaviour]  
4            0            0                     [Inefficiency, Unavailibility]

In [ ]:
# Define a dictionary mapping the original values to their corresponding numbers
mapping = {'Service': 1, 'Negligence': 2, 'Behaviour': 3, 'Cleanliness': 4, 'Pharmacy': 5,
           'Unprofessionalism': 6, 'Inefficiency': 7, 'Unavailability': 8, 'Billing': 9}

# Define a function to apply the mapping to each list element
def map_values(lst_str):
    # Convert the string representation to a list by removing brackets and splitting by comma
    lst = lst_str.strip('[]').split(', ')
    # Map each value in the list to its corresponding number using the mapping dictionary
    return [mapping[val.strip()] for val in lst]

# Apply the function to the column containing string representations of lists
df['Multilabel pred'] = df['Multilabel pred'].apply(map_values)



KeyError: 'Unavailibility'

In [ ]:
df.head()

Full Complaint  Complaint/Non Complaint  \
0  Rainbow hospital will loot your hard earned mo...                        1   
1  My seven-months old baby had second-degree bur...                        1   
2  Very unprofessional .\nShe will not give you e...                        1   
3  The staff are extremely caring and hard workin...                        0   
4  Very expensive Lab Tests and I don't know why ...                        1   

   Service  Negligence  Behaviour  Cleanliness  Pharmacy  Unprofessionalism  \
0      1.0         NaN        NaN          NaN       NaN                NaN   
1      1.0         2.0        3.0          NaN       NaN                6.0   
2      1.0         NaN        NaN          NaN       NaN                6.0   
3      1.0         NaN        3.0          NaN       NaN                6.0   
4      NaN         2.0        NaN          NaN       NaN                NaN   

   Inefficiency  Unavailibility  Billing         Multilabels  word_count  \
0           NaN             NaN      9.0              [1, 9]          58   
1           7.0             NaN      9.0  [1, 2, 3, 6, 7, 9]          91   
2           7.0             NaN      NaN           [1, 6, 7]          63   
3           NaN             NaN      NaN           [1, 3, 6]          24   
4           NaN             NaN      9.0              [2, 9]          39   

   Binary Pred  Predictions                                    Multilabel pred  
0            1            1  [Unprofessionalism, Inefficiency, Unavailibility]  
1            0            0                  [Unprofessionalism, Inefficiency]  
2            1            1                                [Unprofessionalism]  
3            0            0                               [Service, Behaviour]  
4            0            0                     [Inefficiency, Unavailibility]